version: '3'
services:
  react-app:
    build:
      context: ./my-react
    ports:
      - "3000:3000"
    depends_on:
      - strapi-api

  strapi-api:
    build:
      context: ./my-strapi
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data.db
      APP_KEYS: your_app_keys
      API_TOKEN_SALT: your_api_token_salt
      ADMIN_JWT_SECRET: your_admin_jwt_secret
      JWT_SECRET: your_jwt_secret
